# Site settings
title: "Amin Al Hazwani, Designer"
description: "Design & CSS."
baseurl: ""
url: "http://aminalhazwani.com"
permalink: "/:categories/:title/"

# Build settings
markdown: redcarpet

# Exclude files and folders
exclude: 
  - gulp
  - s3_website.yml
  - readme.md
  - package.json
  - Gemfile
  - Gemfile.lock
  - node_modules
  - images

# Plugins
assets:
  css_compressor: sass
  sources:
    - _assets/css

picture:
  source: images/_fullsize
  output: images
  markup: picture
  presets:
    default:
      ppi: [1, 1.5]
      source_large:
        media: "(min-width: 61em)"
        width: 598
      source_medium:
        media: "(min-width: 45.5em)"
        width: 498
      source_default:
        width: 406
    full:
      ppi: [1, 1.5]
      source_large:
        media: "(min-width: 61em)"
        width: 1080
      source_medium:
        media: "(min-width: 45.5em)"
        width: 975
      source_small:
        media: "(min-width: 30.063em)"
        width: 727
      source_default:
        width: 480
    half:

    third:
      ppi: [1, 1.5]
      source_large:
        media: "(min-width: 61em)"
        width: 334
      source_medium:
        media: "(min-width: 45.5em)"
        width: 300
      source_small:
        media: "(min-width: 30.063em)"
        width: 216
      source_default:
        width: 406
