# Site settings
title: "Amin Al Hazwani"
description: "My name is Amin Al Hazwani, and I'm a Berlin based product designer. I design apps and build websites."
keywords: "design,app,web,html,css,development,product,designer"
url: "http://aminalhazwani.com"
email: "amin.alhazwani@gmail.com"
twitter: "@aminalhazwani"
instagram: "@aminalhazwani"

# Build settings
markdown: kramdown
permalink: "/:title/"

# Exclude files and folders
exclude: 
  - gulp
  - s3_website.yml
  - readme.md
  - package.json
  - Gemfile
  - Gemfile.lock
  - node_modules
  - images

# Plugins
assets:
  sources:
    - _assets/css